### ISSUE TITLE
github actions の git config を pyproject.toml を利用するようにしてハードコーディングはやめる

### ISSUE THREAD

**Issue by mizucopo** [mizucopo/stockvalue-exporter#25]
```yaml
- name: Configure Git
  run: |
    git config --global user.name "mizu"
    git config --global user.email "mizu.copo@gmail.com"
```

上記ハードコーディングを停止する。
pyproject.toml の値を参照する。
